[lib]
proc-macro = true

[package]
name = "macro-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.13"
quote = "1.0.26"